// react-components/src/components-show/Pagination/Pagination.tsx
import React, { useMemo, useState } from 'react'
import PaginationLogic from './PaginationLogic'
import { PaginationProps } from './types'

const Pagination: React.FC<PaginationProps> = ({
  data,
  pageSize = 10,
  colNames,
}) => {
  const [currentPage, setCurrentPage] = useState(1)

  const currentTableData = useMemo(() => {
    const firstPageIndex = (currentPage - 1) * pageSize
    const lastPageIndex = firstPageIndex + pageSize
    return data.slice(firstPageIndex, lastPageIndex)
  }, [currentPage])

  return (
    <div className='w-full flex flex-col items-center'>
      <table className='w-full border-collapse'>
        <thead>
          <tr>
            {colNames?.map((name, idx) => {
              return (
                <th className='font-bold text-left bg-[#fafafa] p-2' key={idx}>
                  {name}
                </th>
              )
            })}
          </tr>
        </thead>
        <tbody>
          {currentTableData.map((item, idx) => {
            return (
              <tr
                key={item.id}
                className={`${idx % 2 === 0 ? 'bg-gray-100' : 'bg-white'}`}
              >
                {Object.keys(item).map((key: any) => {
                  return (
                    <td key={key} className='border-b border-gray-200 p-2'>
                      {item[key]}
                    </td>
                  )
                })}
              </tr>
            )
          })}
        </tbody>
      </table>
      <PaginationLogic
        currentPage={currentPage}
        totalCount={data.length}
        pageSize={pageSize}
        onPageChange={(page) => setCurrentPage(page)}
      />
    </div>
  )
}

export default Pagination

// vue-components/src/components-show/Pagination/Pagination.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import PaginationLogic from './PaginationLogic.vue'
import type { PaginationProps } from './types'

const props = withDefaults(defineProps<PaginationProps>(), {
  pageSize: 10,
})

const currentPage = ref(1)

const currentTableData = computed(() => {
  const first = (currentPage.value - 1) * props.pageSize
  const last = first + props.pageSize
  return props.data.slice(first, last)
})

function handlePageChange(page: number) {
  currentPage.value = page
}
</script>

<template>
  <div class="w-full flex flex-col items-center">
    <table class="w-full border-collapse">
      <thead>
        <tr>
          <th
            v-for="(name, idx) in colNames"
            :key="idx"
            class="font-bold text-left bg-[#fafafa] p-2"
          >
            {{ name }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="(item, idx) in currentTableData"
          :key="item.id"
          :class="idx % 2 === 0 ? 'bg-gray-100' : 'bg-white'"
        >
          <td
            v-for="(val, key) in item"
            :key="key"
            class="border-b border-gray-200 p-2"
          >
            {{ val }}
          </td>
        </tr>
      </tbody>
    </table>

    <PaginationLogic
      :currentPage="currentPage"
      :totalCount="data.length"
      :pageSize="pageSize"
      @page-change="handlePageChange"
    />
  </div>
</template>
