// react-components/src/components-show/Calendar/Calendar.tsx
import React, { useState, useMemo } from 'react'

type CalendarDay = {
  date: Date
  isCurrentMonth: boolean
}

const Calendar: React.FC = () => {
  const today = new Date()
  const [currentYear, setCurrentYear] = useState(today.getFullYear())
  const [currentMonth, setCurrentMonth] = useState(today.getMonth())

  const [rangeStartDate, setRangeStartDate] = useState<Date | undefined>()
  const [rangeEndDate, setRangeEndDate] = useState<Date | undefined>()

  const daysInMonth = (year: number, month: number): number =>
    new Date(year, month + 1, 0).getDate()

  const getFirstDayOfMonth = (year: number, month: number): number =>
    new Date(year, month, 1).getDay()

  const isSameDate = (d1: Date, d2: Date): boolean =>
    d1.getFullYear() === d2.getFullYear() &&
    d1.getMonth() === d2.getMonth() &&
    d1.getDate() === d2.getDate()

  const isToday = (date: Date): boolean => isSameDate(date, today)

  const isInRange = (date: Date): boolean =>
    !!rangeStartDate &&
    !!rangeEndDate &&
    date >= rangeStartDate &&
    date <= rangeEndDate

  const isRangeStart = (date: Date): boolean =>
    !!rangeStartDate && isSameDate(date, rangeStartDate)

  const isRangeEnd = (date: Date): boolean =>
    !!rangeEndDate && isSameDate(date, rangeEndDate)

  const selectDate = (date: Date) => {
    if (!rangeStartDate || (rangeStartDate && rangeEndDate)) {
      setRangeStartDate(date)
      setRangeEndDate(undefined)
    } else if (!rangeEndDate) {
      if (date < rangeStartDate) {
        setRangeEndDate(rangeStartDate)
        setRangeStartDate(date)
      } else {
        setRangeEndDate(date)
      }
    }
  }

  const calendarDays: CalendarDay[] = useMemo(() => {
    const days: CalendarDay[] = []
    const firstDay = getFirstDayOfMonth(currentYear, currentMonth)
    const prevMonthLastDate = daysInMonth(currentYear, currentMonth - 1)

    for (let i = firstDay - 1; i >= 0; i--) {
      days.push({
        date: new Date(currentYear, currentMonth - 1, prevMonthLastDate - i),
        isCurrentMonth: false,
      })
    }

    const totalDays = daysInMonth(currentYear, currentMonth)
    for (let i = 1; i <= totalDays; i++) {
      days.push({
        date: new Date(currentYear, currentMonth, i),
        isCurrentMonth: true,
      })
    }

    const remaining = 42 - days.length
    for (let i = 1; i <= remaining; i++) {
      days.push({
        date: new Date(currentYear, currentMonth + 1, i),
        isCurrentMonth: false,
      })
    }

    return days
  }, [currentYear, currentMonth])

  const prevMonth = () => {
    if (currentMonth === 0) {
      setCurrentMonth(11)
      setCurrentYear(currentYear - 1)
    } else {
      setCurrentMonth(currentMonth - 1)
    }
  }

  const nextMonth = () => {
    if (currentMonth === 11) {
      setCurrentMonth(0)
      setCurrentYear(currentYear + 1)
    } else {
      setCurrentMonth(currentMonth + 1)
    }
  }

  const formatDate = (date: Date | undefined) =>
    date ? `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}` : ''

  return (
    <div className='max-w-xl mx-auto p-4'>
      {/* Header */}
      <div className='flex justify-between items-center mb-4'>
        <button
          onClick={prevMonth}
          className='px-3 py-1 bg-gray-200 rounded hover:bg-gray-300'
        >
          ‹
        </button>
        <div className='text-lg font-semibold'>
          {currentYear}年 {currentMonth + 1}月
        </div>
        <button
          onClick={nextMonth}
          className='px-3 py-1 bg-gray-200 rounded hover:bg-gray-300'
        >
          ›
        </button>
      </div>

      {/* Weekdays */}
      <div className='grid grid-cols-7 text-center font-semibold mb-2'>
        {['日', '一', '二', '三', '四', '五', '六'].map((day) => (
          <div key={day}>{day}</div>
        ))}
      </div>

      {/* Calendar Days */}
      <div className='grid grid-cols-7 gap-1'>
        {calendarDays.map((day, index) => {
          const { date, isCurrentMonth } = day
          const isStart = isRangeStart(date)
          const isEnd = isRangeEnd(date)
          const inRange = isInRange(date)
          const today = isToday(date)

          return (
            <div
              key={index}
              onClick={() => selectDate(date)}
              className={`p-2 h-20 border rounded-lg cursor-pointer text-sm transition-all
                ${!isCurrentMonth ? 'bg-gray-100 text-gray-400' : ''}
                ${today ? 'border-blue-500 bg-blue-300' : ''}
                ${isStart ? 'bg-blue-500 font-bold text-white' : ''}
                ${isEnd ? 'bg-blue-500 font-bold text-white' : ''}
                ${
                  inRange && !isStart && !isEnd
                    ? 'bg-blue-100 text-blue-800'
                    : ''
                }
              `}
            >
              {date.getDate()}
            </div>
          )
        })}
      </div>

      {/* Output */}
      <div className='mt-4 text-sm text-gray-700'>
        {rangeStartDate && <div>开始: {formatDate(rangeStartDate)}</div>}
        {rangeEndDate && <div>结束: {formatDate(rangeEndDate)}</div>}
      </div>
    </div>
  )
}

export default Calendar

// vue-components/src/components-show/Calendar/Calendar.vue
<template>
  <div class="max-w-xl mx-auto p-4">
    <!-- Header -->
    <div class="flex justify-between items-center mb-4">
      <button
        @click="prevMonth"
        class="px-3 py-1 bg-gray-200 rounded hover:bg-gray-300"
      >
        ‹
      </button>
      <div class="text-lg font-semibold">
        {{ currentYear }}年 {{ currentMonth + 1 }}月
      </div>
      <button
        @click="nextMonth"
        class="px-3 py-1 bg-gray-200 rounded hover:bg-gray-300"
      >
        ›
      </button>
    </div>

    <!-- Weekdays -->
    <div class="grid grid-cols-7 text-center font-semibold mb-2">
      <div v-for="day in ['日', '一', '二', '三', '四', '五', '六']" :key="day">
        {{ day }}
      </div>
    </div>

    <!-- Calendar Days -->
    <div class="grid grid-cols-7 gap-1">
      <div
        v-for="(day, index) in calendarDays"
        :key="index"
        @click="selectDate(day.date)"
        class="p-2 h-20 border rounded-lg cursor-pointer text-sm transition-all"
        :class="[
          day.isCurrentMonth ? '' : 'bg-gray-100 text-gray-400',
          isToday(day.date) ? 'border-blue-500 bg-blue-300' : '',
          isRangeStart(day.date) ? 'bg-blue-500 font-bold' : '',
          isRangeEnd(day.date) ? 'bg-blue-500 font-bold' : '',
          isInRange(day.date) ? 'bg-blue-100 text-blue-800' : '',
        ]"
      >
        {{ day.date.getDate() }}
      </div>
    </div>

    <!-- Output -->
    <div class="mt-4 text-sm text-gray-700">
      <div v-if="rangeStartDate">开始: {{ formatDate(rangeStartDate) }}</div>
      <div v-if="rangeEndDate">结束: {{ formatDate(rangeEndDate) }}</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'

const today = new Date()
const currentMonth = ref(today.getMonth())
const currentYear = ref(today.getFullYear())

const rangeStartDate = ref<Date | undefined>(undefined)
const rangeEndDate = ref<Date | undefined>(undefined)

// 获取某个月的天数，某个月上月的最后一天
const daysInMonth = (year: number, month: number) =>
  new Date(year, month + 1, 0).getDate()

// 获取某个月的第一天是星期几
const getFirstDayOfMonth = (year: number, month: number) =>
  new Date(year, month, 1).getDay()

const calendarDays = computed(() => {
  const days: { date: Date; isCurrentMonth: boolean }[] = []

  const firstDay = getFirstDayOfMonth(currentYear.value, currentMonth.value)
  const prevMonthLastDate = daysInMonth(
    currentYear.value,
    currentMonth.value - 1
  )

  // Fill previous month days
  for (let i = firstDay - 1; i >= 0; i--) {
    days.push({
      date: new Date(
        currentYear.value,
        currentMonth.value - 1,
        prevMonthLastDate - i
      ),
      isCurrentMonth: false,
    })
  }

  // Current month days
  const totalDays = daysInMonth(currentYear.value, currentMonth.value)
  for (let i = 1; i <= totalDays; i++) {
    days.push({
      date: new Date(currentYear.value, currentMonth.value, i),
      isCurrentMonth: true,
    })
  }

  // Fill next month days
  const remaining = 42 - days.length
  for (let i = 1; i <= remaining; i++) {
    days.push({
      date: new Date(currentYear.value, currentMonth.value + 1, i),
      isCurrentMonth: false,
    })
  }

  return days
})

const prevMonth = () => {
  if (currentMonth.value === 0) {
    currentMonth.value = 11
    currentYear.value--
  } else {
    currentMonth.value--
  }
}

const nextMonth = () => {
  if (currentMonth.value === 11) {
    currentMonth.value = 0
    currentYear.value++
  } else {
    currentMonth.value++
  }
}

const isSameDate = (d1: Date, d2: Date) =>
  d1.getFullYear() === d2.getFullYear() &&
  d1.getMonth() === d2.getMonth() &&
  d1.getDate() === d2.getDate()

const isToday = (date: Date) => isSameDate(date, today)

const isInRange = (date: Date) => {
  return (
    rangeStartDate.value &&
    rangeEndDate.value &&
    date >= rangeStartDate.value &&
    date <= rangeEndDate.value
  )
}

const isRangeStart = (date: Date) =>
  rangeStartDate.value && isSameDate(date, rangeStartDate.value)

const isRangeEnd = (date: Date) =>
  rangeEndDate.value && isSameDate(date, rangeEndDate.value)

// 选择日期时间段的逻辑
const selectDate = (date: Date) => {
  if (!rangeStartDate.value || (rangeStartDate.value && rangeEndDate.value)) {
    rangeStartDate.value = date
    rangeEndDate.value = undefined
  } else if (!rangeEndDate.value) {
    if (date < rangeStartDate.value) {
      rangeEndDate.value = rangeStartDate.value
      rangeStartDate.value = date
    } else {
      rangeEndDate.value = date
    }
  }
}

const formatDate = (date: Date | undefined): string =>
  date ? `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}` : ''
</script>
