// vue-components/src/components-show/Popover/Popover.vue
<template>
  <div
    class="relative inline-block"
    ref="containerRef"
    @mouseenter="handleMouseEnter"
    @mouseleave="handleMouseLeave"
  >
    <div
      class="bg-[#007BFF] text-white p-2.5 cursor-pointer rounded"
      role="button"
      aria-haspopup="true"
      :aria-expanded="isVisible"
      aria-controls="popover-content"
    >
      <slot />
    </div>

    <div
      v-if="isVisible"
      id="popover-content"
      class="absolute top-full left-1/2 mb-2.5 -translate-x-1/2 
      bg-white border border-[#ccc] shadow-lg rounded p-3 
      z-[1000] whitespace-nowrap"
      role="dialog"
      aria-modal="true"
    >
      <slot name="content" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import type { PopoverSlots } from './types'

defineSlots<PopoverSlots>()

const isVisible = ref(false)
const containerRef = ref<HTMLElement | null>(null)

const handleMouseEnter = () => {
  isVisible.value = true
}

const handleMouseLeave = () => {
  isVisible.value = false
}
</script>

// react-components/src/components-show/Popover/Popover.tsx
import type { PopoverProps } from './types'
import React, { useRef, useState } from 'react'

const Popover: React.FC<PopoverProps> = ({ children, content }) => {
  const [isVisible, setIsVisible] = useState(false)
  const containerRef = useRef(null)

  const handleMouseEnter = () => {
    setIsVisible(true)
  }

  const handleMouseLeave = () => {
    setIsVisible(false)
  }

  return (
    <div
      className="relative inline-block"
      ref={containerRef}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
    >
      <div
        className="bg-[#007BFF] text-white p-2.5
        border-none cursor-pointer rounded"
        aria-haspopup="true"
        aria-expanded={isVisible}
        aria-controls="popover-content"
      >
        {children}
      </div>
      {isVisible && (
        <div
          id="popover-content"
          className="absolute top-full translate-y-2 left-1/2 mb-2.5
          -translate-x-1/2 bg-white border-[#ccc] shadow-lg rounded
          p-3 z-[1000] whitespace-nowrap "
          role="dialog"
          aria-modal="true"
        >
          {content}
        </div>
      )}
    </div>
  )
}

export default Popover
