// react-components/src/components-show/Affix/Affix.tsx
import React, { useEffect, useRef, useState } from 'react'
import { AffixProps } from './types'

export default function Affix({
  top,
  left = 0,
  children,
  offset = 0,
}: AffixProps) {
  const elementRef = useRef<HTMLDivElement | null>(null)

  const [affixed, setAffixed] = useState(false)
  // placeholder for width to prevent layout shift
  const [width, setWidth] = useState<number | null>(null)

  useEffect(() => {
    const el = elementRef.current
    if (!el) return

    const rect = el.getBoundingClientRect()
    const scrollY = window.scrollY || window.pageYOffset
    const distanceToBody = scrollY + rect.top

    const handleScroll = () => {
      requestAnimationFrame(() => {
        const shouldAffix = window.scrollY > distanceToBody - top - offset
        if (shouldAffix !== affixed) {
          setAffixed(shouldAffix)
          if (shouldAffix) {
            setWidth(el.offsetWidth)
          }
        }
      })
    }

    window.addEventListener('scroll', handleScroll)
    window.addEventListener('resize', handleScroll)

    return () => {
      window.removeEventListener('scroll', handleScroll)
      window.removeEventListener('resize', handleScroll)
    }
  }, [top, offset, affixed])

  const affixStyle: React.CSSProperties = affixed
    ? {
        position: 'fixed',
        top: `${top}px`,
        left: `${left}px`,
        width: width ?? 'auto',
        zIndex: 1,
      }
    : {}

  return (
    <>
      {/** 占位元素防止页面跳动 */}
      {affixed && (
        <div
          style={{
            width: width ?? 'auto',
            height: elementRef.current?.offsetHeight,
          }}
        />
      )}
      <div ref={elementRef} style={affixStyle}>
        {children}
      </div>
    </>
  )
}

// vue-components/src/components-show/Affix/Affix.vue
<template>
  <div>
    <!-- 占位元素防止页面跳动 -->
    <div
      v-if="affixed"
      :style="{ width: width ? `${width}px` : 'auto', height: `${height}px` }"
    />
    <div
      ref="elementRef"
      :style="
        affixed
          ? {
              position: 'fixed',
              top: `${props.top}px`,
              left: `${props.left}px`,
              width: width ? `${width}px` : 'auto',
              zIndex: 1,
            }
          : {}
      "
    >
      <slot />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue'
import type { AffixProps } from './types'

const props = withDefaults(defineProps<AffixProps>(), {
  left: 0,
  offset: 0,
})

const elementRef = ref<HTMLElement | null>(null)
const affixed = ref(false)
const width = ref<number | null>(null)
const height = ref<number>(0)

const handleScroll = () => {
  const el = elementRef.value
  if (!el) return

  requestAnimationFrame(() => {
    const rect = el.getBoundingClientRect()
    const scrollY = window.scrollY || window.pageYOffset

    const shouldAffix = scrollY + Math.abs(rect.top) > props.offset
    if (shouldAffix !== affixed.value) {
      affixed.value = shouldAffix
      if (shouldAffix && elementRef.value) {
        width.value = elementRef.value.offsetWidth
        height.value = elementRef.value.offsetHeight
      }
    }
  })
}

onMounted(() => {
  window.addEventListener('scroll', handleScroll)
  window.addEventListener('resize', handleScroll)
})

onBeforeUnmount(() => {
  window.removeEventListener('scroll', handleScroll)
  window.removeEventListener('resize', handleScroll)
})
</script>
