// vue-components/src/components-show/Rate/ForShow.vue
<script setup lang="ts">
import { ref } from 'vue'
import Rate from './Rate.vue'
const curScore = ref<number>(3)
</script>

<template>
  <div class="hello">
    <h3>显示数字：</h3>
    <Rate v-model:score="curScore" :disabled="false" />
    <h3>只读，显示数字：</h3>
    <Rate :score="3" :disabled="true" showText />
  </div>
</template>

// react-components/src/components-show/Rate/ForShow.tsx
import { useState } from 'react'
import Rate from './Rate'

export default function App() {
  const [curScore, setCurScore] = useState<number>(3)

  return (
    <div className="p-6 space-y-4">
      <h3 className="font-semibold text-lg">显示数字：</h3>
      <Rate score={curScore} onScoreChange={setCurScore} disabled={false} />

      <h3 className="font-semibold text-lg">只读，显示数字：</h3>
      <Rate score={3} disabled={true} showText />
    </div>
  )
}
