// react-components/src/components-show/VirtualList/VirtualList.tsx
import React from 'react'
import { DynamicSizeList, type DynamicRow } from './DynamicSizeList'
import { FixedSizeList, type FixedRow } from './FixedSizeList'

const heightCache: Record<number, number> = {}
const Row: React.FC<DynamicRow> = ({ index }) => {
  if (heightCache[index] === undefined) {
    heightCache[index] = 20 + Math.floor(Math.random() * 50)
  }

  const style: React.CSSProperties = {
    height: heightCache[index],
  }
  const backgroundColorClass = index % 2 === 0 ? 'bg-blue-100' : 'bg-white'

  return (
    <div
      className={`flex items-center justify-center ${backgroundColorClass}`}
      style={style}
    >
      Row {index}
    </div>
  )
}

const FixedRow: React.FC<FixedRow> = ({ index, style }) => {
  const backgroundColorClass = index % 2 === 0 ? 'bg-blue-100' : 'bg-white'

  return (
    <div
      className={`w-full ${backgroundColorClass} flex items-center justify-center`}
      style={{ ...style }}
    >
      Row {index}
    </div>
  )
}

const VirtualList: React.FC = () => {
  return (
    <div className='flex w-full justify-around'>
      <DynamicSizeList height={300} width={300} itemCount={1000}>
        {Row}
      </DynamicSizeList>
      <FixedSizeList height={300} width={300} itemSize={50} itemCount={1000}>
        {FixedRow}
      </FixedSizeList>
    </div>
  )
}

export default VirtualList

// vue-components/src/components-show/VirtualList/VirtualList.vue
<script setup lang="ts">
import FixedSizeList from './FixedSizeList.vue'
import DynamicSizeList from './DynamicSizeList.vue'
</script>

<template>
  <div class="flex w-full justify-around items-center">
    <DynamicSizeList :height="300" :width="300" :itemCount="1000000" :item-estimated-size="50">
      <template #default="{ index }">
        <div 
        :style="{height: 20 + Math.floor(Math.random() * 50) + 'px'}" 
        :class="[index & 1 ? 'bg-blue-100' : '', 'flex', 'items-center', 'justify-center']"
        >Row {{ index }}</div>
      </template>
    </DynamicSizeList>

    <FixedSizeList :height="300" :width="300" :item-size="50" :item-count="1000">
      <template #default="{ index, style }">
        <div :style="style" :class="index & 1 ? 'bg-blue-100' : ''">Row {{ index }}</div>
      </template>
    </FixedSizeList>
  </div>
</template>
