// react-components/src/components-show/Progress/DisContinuous.tsx
import React from 'react'
import { DisContinuousProps } from './types'

export const DisContinuous: React.FC<DisContinuousProps> = ({
  step,
  currentStep,
}: DisContinuousProps) => {
  return (
    <div className='inline-block relative'>
      <span className='absolute left-1/2 -translate-x-1/2 bottom-6
      text-[#6a1b9a] font-bold'>
        {currentStep}/{step}
      </span>
      {Array.from({ length: step }, (_, i) => i + 1).map((s) => (
        <div
          key={s}
          className={`inline-block h-5 w-5 rounded mr-[1px] ${
            s <= currentStep ? 'bg-[#6a1b9a]' : 'bg-[#e0e0de]'
          }`}
        />
      ))}
    </div>
  )
}

// vue-components/src/components-show/Progress/DisContinuous.vue
<template>
  <div class="inline-block relative">
    <span
      class="absolute left-1/2 -translate-x-1/2 bottom-6 text-[#6a1b9a] font-bold"
    >
      {{ currentStep }}/{{ step }}
    </span>
    <div
      v-for="s in step"
      :key="s"
      :class="[
        'inline-block h-5 w-5 rounded mr-[1px]',
        s <= currentStep ? 'bg-[#6a1b9a]' : 'bg-[#e0e0de]',
      ]"
    />
  </div>
</template>

<script setup lang="ts">
import type { DisContinuousProps } from './types'

defineProps<DisContinuousProps>()
</script>
