// vue-components/src/components-show/Toast/Toast.vue
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import type { ToastProps } from './types'

defineOptions({
  name: 'Toast',
})

const props = withDefaults(defineProps<ToastProps>(), {
  duration: 1000
})

const visible = ref<boolean>(false)
const message = ref<string>('')
// if not expose visible, it will not be able to change visible in other components
defineExpose({
  visible,
  message,
})

onMounted(() => {
  visible.value = false
})

watch(visible, (value) => {
  // only set visible to false when it is true
  if (value) {
    setTimeout(() => {
      visible.value = false
    }, props.duration)
  }
})
</script>

<template>
  <transition name="toast">
    <div v-if="visible" class="fixed top-1/2 left-1/2 transform 
    -translate-x-1/2 -translate-y-1/2 bg-gray-800 
    text-white p-2 rounded z-[9999]">
      <div class="inline-block mx-2.5">{{ message }}</div>
    </div>
  </transition>
</template>

<style scoped>
/* toast animation */
.toast-enter-active,
.toast-leave-active {
  transition: opacity 0.5s ease;
}

.toast-enter-from,
.toast-leave-to {
  opacity: 0;
}
</style>

// react-components/src/components-show/Toast/Toast.tsx
import React, { useEffect, useState } from 'react'

type ToastProps = {
  message: string
  duration: number
}

const Toast: React.FC<ToastProps> = ({ message, duration }) => {
  const [isVisible, setIsVisible] = useState(true)
  const [opacity, setOpacity] = useState(0)

  useEffect(() => {
    setOpacity(1)

    const timer1 = setTimeout(() => {
      setOpacity(0)
    }, duration)

    const timer2 = setTimeout(() => {
      setIsVisible(false)
    }, duration + 500)

    return () => {
      clearTimeout(timer1)
      clearTimeout(timer2)
    }
  }, [])

  return (
    isVisible && (
      <div
        className={`fixed top-1/3 left-1/2 transform 
        -translate-x-1/2 -translate-y-1/2 bg-gray-800 
        text-white p-2 rounded z-[9999] transition-opacity 
        duration-500 opacity-${opacity}`}
      >
        <div className='inline-block mx-2.5'>{message}</div>
      </div>
    )
  )
}

export default Toast
